<?php

namespace AppBundle\Repository;

/**
 * commerceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class commerceRepository extends \Doctrine\ORM\EntityRepository
{

    
}
